[tool.poetry]
name = "dronefly-core"
version = "0.2.0"
description = "Core dronefly components"
authors = ["Ben Armstrong <synrg@debian.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
	{ include = "dronefly/core" },
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
pyinaturalist = { git = "https://github.com/niconoe/pyinaturalist", rev = "472f30c3fa5d4c9dd43808ab793f1fa830768722" }
pytest-mock = "^3.6.1"
dateparser = "^1.1.1"
inflect = "^5.3.0"

[tool.poetry.dev-dependencies]
black = "^21.8-beta.0"
pytest = "^6.2.5"
pylint = "^2.10.2"
pytest-asyncio = "^0.16.0"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
